import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { MainHeader } from "./home-components/main-header";
import Footer from "@/components/footer";
import { CartDrawer } from "@/components/cart-drawer";

const inter = Nunito_Sans({
  subsets: ["latin"],
  display: "swap", // Melhora a performance de carregamento da fonte
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-pink-50 text-gray-700`}
      >
        <SidebarProvider>
          <SidebarInset className="flex flex-col min-h-screen">
            <MainHeader />
            <CartDrawer />
            <main className="flex-1">{children}</main>
            <Footer />
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
